package BaseIDLs;

class BaseData
{
    /* Comment for Id, Line 1 */
    /* Comment for Id, Line 2 */

    // skipped comment

    /* Comment for Id, Line 3 */
    // skipped comment
    int Id;

    /* Comment for Name, Line 1 */

    /* Comment for Name, Line 2 */

    /* Comment for Name, Line 3 */

    string  Name;

}