/*
 * TopicConfigTool.java
 *
 * Created on den 1 augusti 2007, 16:06
 */

package idlcompiler.gui;

import Exceptions.TopicConfigFileMissingException;
import idlcompiler.files.Project;
import java.awt.Component;
import java.awt.TextComponent;
import java.util.Vector;
import javax.swing.JOptionPane;
import ops.StaticManager;
import ops.Topic;

/**
 *
 * @author  xangr
 */
public class TopicConfigTool extends javax.swing.JFrame
{
    Vector<String> topicListData = new Vector<String>();
    Project theProject;
    /** Creates new form TopicConfigTool */
    public TopicConfigTool(Project project)
    {
        this.theProject = project;
        initComponents();
        parseTopicConfig(project);        
        topicList.setListData(topicListData);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addTopicButton = new javax.swing.JButton();
        newTopicNameTextField = new java.awt.TextField();
        newTopicTypeTextField = new java.awt.TextField();
        removeSelectedButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        topicList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        basePortTextField = new javax.swing.JTextField();
        generateConfigFileButton = new javax.swing.JButton();
        fileNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Topic");

        jLabel2.setText("Type");

        addTopicButton.setText("Add");
        addTopicButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addTopicButtonActionPerformed(evt);
            }
        });

        newTopicNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newTopicNameTextFieldActionPerformed(evt);
            }
        });

        removeSelectedButton.setText("Remove selected");
        removeSelectedButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                removeSelectedButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(newTopicNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(jLabel2))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(removeSelectedButton)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(newTopicTypeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(9, 9, 9)
                            .add(addTopicButton))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(newTopicNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, addTopicButton, 0, 0, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, newTopicTypeTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(removeSelectedButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(topicList);

        jLabel3.setText("Base port");

        basePortTextField.setText("15000");

        generateConfigFileButton.setText("Generate Config File");
        generateConfigFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generateConfigFileButtonActionPerformed(evt);
            }
        });

        fileNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fileNameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("File name");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(basePortTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fileNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(generateConfigFileButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(basePortTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(generateConfigFileButton)
                    .add(jLabel4)
                    .add(fileNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeSelectedButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeSelectedButtonActionPerformed
    {//GEN-HEADEREND:event_removeSelectedButtonActionPerformed

        topicListData.remove(topicList.getSelectedValue());
        topicList.updateUI();
    }//GEN-LAST:event_removeSelectedButtonActionPerformed

    private void generateConfigFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generateConfigFileButtonActionPerformed
    {//GEN-HEADEREND:event_generateConfigFileButtonActionPerformed
        String outText = "<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n" +
                         "<config>\n\t" ;
        int basePort = Integer.parseInt(basePortTextField.getText());
        int i = 0;
        for (String  s : topicListData)
        {
            int port = basePort + i;
            outText += "\t<" + s + " />\n";
            i++;
            
        }
        outText += "</config>";
        theProject.getTopicConfigFile().setText(outText);
        theProject.getTopicConfigFile().save();
        try
        {
            theProject.save();
        } 
        catch (TopicConfigFileMissingException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage() + ": " + "Set a Topic Config File before saving project.");
            return;
        }
        
        
        
    }//GEN-LAST:event_generateConfigFileButtonActionPerformed

    private void fileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fileNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_fileNameTextFieldActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_fileNameTextFieldActionPerformed

    private void addTopicButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addTopicButtonActionPerformed
    {//GEN-HEADEREND:event_addTopicButtonActionPerformed
        String newTopicString = "topic name =\"" + newTopicNameTextField.getText() + "\" type = \"" + newTopicTypeTextField.getText() + "\"";
        topicListData.add(newTopicString);
        topicList.updateUI();
    }//GEN-LAST:event_addTopicButtonActionPerformed

    private void newTopicNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newTopicNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_newTopicNameTextFieldActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_newTopicNameTextFieldActionPerformed
    
    

    private void parseTopicConfig(Project project)
    {
        
        
        try
        {
            String topicConfigFile = "file:///" + project.getRunDirectory() + "/" + project.getTopicConfigFile().getName();
            //StaticManager.getManager();
            topicConfigFile = topicConfigFile.replace("\\", "/");
            StaticManager manager = StaticManager.reInitializeManager(topicConfigFile);
            basePortTextField.setText("" + manager.getTopics().get(0).getPort());
            
            
            for (Topic t : manager.getTopics())
            {
                String nextTopicString = "topic name =\"" + t.getName() + "\" type = \"" + t.getTypeID() + "\"";
                topicListData.add(nextTopicString);
                
            }
        }
        catch (Exception e)
        {
            //continue with empty file...
        }
        fileNameTextField.setText(project.getTopicConfigFile().getName());
        topicList.updateUI();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTopicButton;
    private javax.swing.JTextField basePortTextField;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JButton generateConfigFileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField newTopicNameTextField;
    private java.awt.TextField newTopicTypeTextField;
    private javax.swing.JButton removeSelectedButton;
    private javax.swing.JList topicList;
    // End of variables declaration//GEN-END:variables
    
}
