/*
 * OptionsTool.java
 *
 * Created on den 21 december 2007, 08:28
 */
package idlcompiler.gui;

import idlcompiler.files.Project;
import idlcompiler.files.TopicConfigFile;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import util.FileHelper;

/**
 *
 * @author  angr
 */
public class OptionsTool extends javax.swing.JFrame
{

    private Project theProject;
    private GUI parentGUI;

    /** Creates new form OptionsTool */
    public OptionsTool(Project theProject, GUI parentGUI)
    {
        this.parentGUI = parentGUI;
        this.theProject = theProject;
        initComponents();      
        takeProjectOptions();
     
    }
    private void takeProjectOptions()
    {
        jarDepList.setListData(this.theProject.getJarDependencies());
        topicConfigPackageTextField.setText(theProject.getTopicConfigPackage());
        topicConfigFileTextField.setText(
                FileHelper.getRelativePath(new File(theProject.getRunDirectory()), 
                theProject.getTopicConfigFile().getFile()));
        genJavaCheckBox.setSelected(theProject.isJavaGenerationEnabled());
        genCSCheckBox.setSelected(theProject.isCsGenerationEnabled());
        genCppCheckBox.setSelected(theProject.isCppGenerationEnabled());
        buildAndJarCheckBox.setSelected(theProject.isBuildAndJarEnabled());
    }

    private void applyOptions() throws IOException
    {
        this.theProject.setTopicConfigPackage(topicConfigPackageTextField.getText());
        this.theProject.setTopicConfig(new TopicConfigFile(new File(theProject.getRunDirectory() + "/" + topicConfigFileTextField.getText())));
        this.theProject.enableCodeHighLighting(enableCodeHighLigthingCheckBox.isSelected());
        this.theProject.enableJavaGeneration(genJavaCheckBox.isSelected());
        this.theProject.enableCppGeneration(genCppCheckBox.isSelected());
        this.theProject.enableCsGeneration(genCSCheckBox.isSelected());
        this.theProject.enableBuildAndJar(buildAndJarCheckBox.isSelected());
        
        parentGUI.updateProjectGUIItems();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        codeGenPanel = new javax.swing.JPanel();
        genJavaCheckBox = new javax.swing.JCheckBox();
        genCppCheckBox = new javax.swing.JCheckBox();
        genCSCheckBox = new javax.swing.JCheckBox();
        buildAndJarCheckBox = new javax.swing.JCheckBox();
        jarDepScrollPane = new javax.swing.JScrollPane();
        jarDepList = new javax.swing.JList();
        jarDepLabel = new javax.swing.JLabel();
        removeJarDepButton = new javax.swing.JButton();
        addJarDepButton = new javax.swing.JButton();
        topicConfigPanel = new javax.swing.JPanel();
        topicConfigPackageTextField = new javax.swing.JTextField();
        topicConfigPackageLabel = new javax.swing.JLabel();
        generateTopicConfigFileCheckBox = new javax.swing.JCheckBox();
        topicConfigFileLabel = new javax.swing.JLabel();
        topicConfigFileTextField = new javax.swing.JTextField();
        topicConfigFileBrowseButton = new javax.swing.JButton();
        editorPanel = new javax.swing.JPanel();
        enableCodeHighLigthingCheckBox = new javax.swing.JCheckBox();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        genJavaCheckBox.setSelected(true);
        genJavaCheckBox.setText("Generate Java code");

        genCppCheckBox.setSelected(true);
        genCppCheckBox.setText("Generate C++ code");

        genCSCheckBox.setText("Generate C# code");
        genCSCheckBox.setEnabled(false);

        buildAndJarCheckBox.setSelected(true);
        buildAndJarCheckBox.setText("Build and Jar Java code ");

        jarDepScrollPane.setViewportView(jarDepList);

        jarDepLabel.setText("Jar file dependencies");

        removeJarDepButton.setText("Remove");
        removeJarDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJarDepButtonActionPerformed(evt);
            }
        });

        addJarDepButton.setText("Add...");
        addJarDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJarDepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout codeGenPanelLayout = new javax.swing.GroupLayout(codeGenPanel);
        codeGenPanel.setLayout(codeGenPanelLayout);
        codeGenPanelLayout.setHorizontalGroup(
            codeGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codeGenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(codeGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genJavaCheckBox)
                    .addComponent(genCppCheckBox)
                    .addComponent(genCSCheckBox)
                    .addComponent(buildAndJarCheckBox)
                    .addGroup(codeGenPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(codeGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jarDepLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, codeGenPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(codeGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(codeGenPanelLayout.createSequentialGroup()
                                        .addComponent(addJarDepButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeJarDepButton))
                                    .addComponent(jarDepScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        codeGenPanelLayout.setVerticalGroup(
            codeGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codeGenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genJavaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genCppCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genCSCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildAndJarCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jarDepLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jarDepScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(codeGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJarDepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeJarDepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Code Generation", codeGenPanel);

        topicConfigPackageTextField.setText("topicconfig");

        topicConfigPackageLabel.setText("Package for topic config class");

        generateTopicConfigFileCheckBox.setSelected(true);
        generateTopicConfigFileCheckBox.setText("Generate a Topic config class");
        generateTopicConfigFileCheckBox.setEnabled(false);

        topicConfigFileLabel.setText("Topic config file (Relative to project file)");

        topicConfigFileTextField.setText("TopicConfig.xml");

        topicConfigFileBrowseButton.setText("Browse");

        javax.swing.GroupLayout topicConfigPanelLayout = new javax.swing.GroupLayout(topicConfigPanel);
        topicConfigPanel.setLayout(topicConfigPanelLayout);
        topicConfigPanelLayout.setHorizontalGroup(
            topicConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topicConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topicConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topicConfigPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(topicConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topicConfigPackageLabel)
                            .addComponent(topicConfigPackageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topicConfigFileLabel)
                            .addGroup(topicConfigPanelLayout.createSequentialGroup()
                                .addComponent(topicConfigFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(topicConfigFileBrowseButton))))
                    .addComponent(generateTopicConfigFileCheckBox))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        topicConfigPanelLayout.setVerticalGroup(
            topicConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topicConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateTopicConfigFileCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topicConfigPackageLabel)
                .addGap(1, 1, 1)
                .addComponent(topicConfigPackageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(topicConfigFileLabel)
                .addGap(1, 1, 1)
                .addGroup(topicConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicConfigFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topicConfigFileBrowseButton))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Topic Config", topicConfigPanel);

        enableCodeHighLigthingCheckBox.setSelected(true);
        enableCodeHighLigthingCheckBox.setText("Enable code highlighting");
        enableCodeHighLigthingCheckBox.setEnabled(false);

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enableCodeHighLigthingCheckBox)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        editorPanelLayout.setVerticalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enableCodeHighLigthingCheckBox)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editor", editorPanel);

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyButton)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        try
        {
            applyOptions();
        } 
        catch (IOException ex)
        {
            GUIHelper.showErrorMessage("All options could not be applied.", this);
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    private void addJarDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJarDepButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new JarFileFilter());
        fc.setAcceptAllFileFilterUsed(false);
        fc.setVisible(true);
        
        int result = fc.showOpenDialog(this);
        
        if(result == JFileChooser.APPROVE_OPTION)
        {
            theProject.getJarDependencies().add(FileHelper.getRelativePath(new File(theProject.getRunDirectory()), new File(fc.getSelectedFile().getPath())));
        }
        jarDepList.updateUI();
        
    }//GEN-LAST:event_addJarDepButtonActionPerformed

    private void removeJarDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJarDepButtonActionPerformed
        theProject.getJarDependencies().remove(jarDepList.getSelectedValue());
        jarDepList.updateUI();
    }//GEN-LAST:event_removeJarDepButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try
        {
            applyOptions();
        } 
        catch (IOException ex)
        {
            GUIHelper.showErrorMessage("All options could not be applied.", this);
        }
        
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJarDepButton;
    private javax.swing.JButton applyButton;
    private javax.swing.JCheckBox buildAndJarCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel codeGenPanel;
    private javax.swing.JPanel editorPanel;
    private javax.swing.JCheckBox enableCodeHighLigthingCheckBox;
    private javax.swing.JCheckBox genCSCheckBox;
    private javax.swing.JCheckBox genCppCheckBox;
    private javax.swing.JCheckBox genJavaCheckBox;
    private javax.swing.JCheckBox generateTopicConfigFileCheckBox;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jarDepLabel;
    private javax.swing.JList jarDepList;
    private javax.swing.JScrollPane jarDepScrollPane;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeJarDepButton;
    private javax.swing.JButton topicConfigFileBrowseButton;
    private javax.swing.JLabel topicConfigFileLabel;
    private javax.swing.JTextField topicConfigFileTextField;
    private javax.swing.JLabel topicConfigPackageLabel;
    private javax.swing.JTextField topicConfigPackageTextField;
    private javax.swing.JPanel topicConfigPanel;
    // End of variables declaration//GEN-END:variables

    
}
