/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefaultOptionsPanel.java
 *
 * Created on 2009-jun-09, 15:38:22
 */

package ops.netbeansmodules.idlsupport;


/**
 *
 * @author angr
 */
public class DefaultOptionsPanel extends javax.swing.JPanel {

    /** Creates new form DefaultOptionsPanel */
    public DefaultOptionsPanel() {
        initComponents();
    }

    void load()
    {
        // TODO read settings and initialize GUI
        // Example:
        // someCheckBox.setSelected(Preferences.userNodeForPackage(OPSOptionsPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(OPSOptionsPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

//    public Vector<JarDependency> javaBuildJarDependencies = new Vector<JarDependency>();
//    public boolean generateOPSConfigClass = false;
//    public boolean opsConfigClassNamespace = false;
//    public boolean generateOPSConfigXMLFileFromSourceComments = false;
//    public boolean addChecksumToConfig = false;
//    public String vsExampleTopicName = "";
//    public String vsExampleDataType = "";
//    public String vsExampleDomainID = "";
//    public boolean vsExampleEnabled = false;
//    private Vector<Property> properties = new Vector<Property>();

    void store()
    {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(OPSOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(OPSOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText(org.openide.util.NbBundle.getMessage(DefaultOptionsPanel.class, "DefaultOptionsPanel.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(496, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
