/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ops.netbeansmodules.idlsupport;

import java.io.File;
import javax.swing.JFileChooser;
import ops.netbeansmodules.idlsupport.projectproperties.JarDependency;
import ops.netbeansmodules.idlsupport.projectproperties.Property;
import ops.netbeansmodules.util.FileHelper;
import ops.netbeansmodules.util.JarFileFilter;
import ops.netbeansmodules.util.DllFileFilter;
import ops.netbeansmodules.idlsupport.projectproperties.Property;

final class OPSOptionsPanel extends javax.swing.JPanel {

    private final OPSOptionsOptionsPanelController controller;

    OPSOptionsPanel(OPSOptionsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        godeGeneratorsTabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        genCppCheckBox = new javax.swing.JCheckBox();
        genJavaCheckBox = new javax.swing.JCheckBox();
        genCsCheckBox = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        buildJavaCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jarDepList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        addJarDepButton = new javax.swing.JButton();
        removeJarDepButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        buildCsCheckBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        dllDepList = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        addDllDepButton = new javax.swing.JButton();
        removeDllDepButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        defaultConfigFileLabel = new javax.swing.JLabel();
        defaultConfigFileTextField = new javax.swing.JTextField();
        changeDefaultConfigFileButton = new javax.swing.JButton();
        genConfigFromSourceCommentsCheckBox = new javax.swing.JCheckBox();
        domainIDTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buildDebugProjectCheckBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        vsExampleEnableCheckBox = new javax.swing.JCheckBox();
        vsExampleDomainTextField = new javax.swing.JTextField();
        vsExampleTopicTextField = new javax.swing.JTextField();
        vsExampleDataTypeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel4.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(genCppCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.genCppCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(genJavaCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.genJavaCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(genCsCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.genCsCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genCppCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genJavaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genCsCheckBox)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genCppCheckBox)
                    .addComponent(genJavaCheckBox)
                    .addComponent(genCsCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel7.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buildJavaCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.buildJavaCheckBox.text")); // NOI18N

        jScrollPane1.setViewportView(jarDepList);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addJarDepButton, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.addJarDepButton.text")); // NOI18N
        addJarDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJarDepButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeJarDepButton, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.removeJarDepButton.text")); // NOI18N
        removeJarDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJarDepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(buildJavaCheckBox)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(addJarDepButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeJarDepButton))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(buildJavaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJarDepButton)
                    .addComponent(removeJarDepButton)))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel6.text")); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel8.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buildCsCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.buildCsCheckBox.text")); // NOI18N

        jScrollPane2.setViewportView(dllDepList);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addDllDepButton, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.addDllDepButton.text")); // NOI18N
        addDllDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDllDepButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeDllDepButton, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.removeDllDepButton.text")); // NOI18N
        removeDllDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDllDepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(addDllDepButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeDllDepButton))
                    .addComponent(buildCsCheckBox)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(buildCsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDllDepButton)
                    .addComponent(removeDllDepButton)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        godeGeneratorsTabs.addTab(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel5.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(defaultConfigFileLabel, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.defaultConfigFileLabel.text")); // NOI18N

        defaultConfigFileTextField.setText(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.defaultConfigFileTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(changeDefaultConfigFileButton, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.changeDefaultConfigFileButton.text")); // NOI18N
        changeDefaultConfigFileButton.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(genConfigFromSourceCommentsCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.genConfigFromSourceCommentsCheckBox.text")); // NOI18N
        genConfigFromSourceCommentsCheckBox.setEnabled(false);

        domainIDTextField.setText(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.domainIDTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(buildDebugProjectCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.buildDebugProjectCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(buildDebugProjectCheckBox)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(defaultConfigFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(changeDefaultConfigFileButton))
                                .addComponent(defaultConfigFileLabel)
                                .addComponent(genConfigFromSourceCommentsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                            .addGap(31, 31, 31))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(domainIDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                            .addContainerGap()))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(buildDebugProjectCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(defaultConfigFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultConfigFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeDefaultConfigFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genConfigFromSourceCommentsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(domainIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel7.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        godeGeneratorsTabs.addTab(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel6.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(vsExampleEnableCheckBox, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.vsExampleEnableCheckBox.text")); // NOI18N

        vsExampleDomainTextField.setText(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.vsExampleDomainTextField.text")); // NOI18N

        vsExampleTopicTextField.setText(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.vsExampleTopicTextField.text")); // NOI18N
        vsExampleTopicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsExampleTopicTextFieldActionPerformed(evt);
            }
        });

        vsExampleDataTypeTextField.setText(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.vsExampleDataTypeTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vsExampleEnableCheckBox)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vsExampleDomainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vsExampleTopicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(vsExampleDataTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(vsExampleEnableCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vsExampleDomainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsExampleTopicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsExampleDataTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jPanel6.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel6.AccessibleContext.accessibleName")); // NOI18N

        godeGeneratorsTabs.addTab(org.openide.util.NbBundle.getMessage(OPSOptionsPanel.class, "OPSOptionsPanel.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(godeGeneratorsTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(godeGeneratorsTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vsExampleTopicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsExampleTopicTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_vsExampleTopicTextFieldActionPerformed

    private void addJarDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJarDepButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new JarFileFilter());
        fc.setAcceptAllFileFilterUsed(false);
        fc.setVisible(true);

        int result = fc.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            OPSIDLProject.defaultProperties.javaBuildJarDependencies.add(
                    new JarDependency(
                    fc.getSelectedFile().getPath()));
            //                    FileHelper.unixSlashed(
            //                        FileHelper.getRelativePath(
            //                            new File(currentDirectory),
            //                            new File(fc.getSelectedFile().getPath())))));
        }
        jarDepList.updateUI();
}//GEN-LAST:event_addJarDepButtonActionPerformed

    private void removeJarDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJarDepButtonActionPerformed
        // TODO add your handling code here:
        int idx = jarDepList.getSelectedIndex();
        if (idx >= 0) {
            OPSIDLProject.defaultProperties.javaBuildJarDependencies.remove(idx);
            jarDepList.updateUI();
        }
}//GEN-LAST:event_removeJarDepButtonActionPerformed

    private void addDllDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDllDepButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new DllFileFilter());
        fc.setAcceptAllFileFilterUsed(false);
        fc.setVisible(true);

        int result = fc.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            OPSIDLProject.defaultProperties.csBuildDllDependencies.add(
                    new JarDependency(
                    fc.getSelectedFile().getPath()));
        }
        dllDepList.updateUI();
    }//GEN-LAST:event_addDllDepButtonActionPerformed

    private void removeDllDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDllDepButtonActionPerformed
        // TODO add your handling code here:
        int idx = dllDepList.getSelectedIndex();
        if (idx >= 0) {
            OPSIDLProject.defaultProperties.csBuildDllDependencies.remove(idx);
            dllDepList.updateUI();
        }
    }//GEN-LAST:event_removeDllDepButtonActionPerformed

    void load()
    {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(OPSOptionsPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(OPSOptionsPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        genCppCheckBox.setSelected(OPSIDLProject.defaultProperties.generateCpp);
        genJavaCheckBox.setSelected(OPSIDLProject.defaultProperties.generateJava);
        genCsCheckBox.setSelected(OPSIDLProject.defaultProperties.generateCS);

        buildJavaCheckBox.setSelected(OPSIDLProject.defaultProperties.buildJava);
        jarDepList.setListData(OPSIDLProject.defaultProperties.javaBuildJarDependencies);

        buildCsCheckBox.setSelected(OPSIDLProject.defaultProperties.buildCS);
        dllDepList.setListData(OPSIDLProject.defaultProperties.csBuildDllDependencies);

        buildDebugProjectCheckBox.setSelected(OPSIDLProject.defaultProperties.buildDebugProject);
        defaultConfigFileTextField.setText(OPSIDLProject.defaultProperties.defaultOPSTopicConfigFile);
        domainIDTextField.setText(OPSIDLProject.defaultProperties.debugProjDomainID);

        vsExampleEnableCheckBox.setSelected(Boolean.parseBoolean(OPSIDLProject.defaultProperties.getPropertyValue("vsExampleEnabled", "false")));
        vsExampleTopicTextField.setText(OPSIDLProject.defaultProperties.getPropertyValue("vsExampleTopicName", ""));
        vsExampleDataTypeTextField.setText(OPSIDLProject.defaultProperties.getPropertyValue("vsExampleDataType", ""));
        vsExampleDomainTextField.setText(OPSIDLProject.defaultProperties.getPropertyValue("vsExampleDomainID", ""));
    }

    void store()
    {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(OPSOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(OPSOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        OPSIDLProject.defaultProperties.generateCpp = genCppCheckBox.isSelected();
        OPSIDLProject.defaultProperties.generateJava = genJavaCheckBox.isSelected();
        OPSIDLProject.defaultProperties.generateCS = genCsCheckBox.isSelected();

        OPSIDLProject.defaultProperties.buildJava = buildJavaCheckBox.isSelected();
        OPSIDLProject.defaultProperties.buildCS = buildCsCheckBox.isSelected();

        OPSIDLProject.defaultProperties.buildDebugProject = buildDebugProjectCheckBox.isSelected();
        OPSIDLProject.defaultProperties.defaultOPSTopicConfigFile = defaultConfigFileTextField.getText();
        OPSIDLProject.defaultProperties.debugProjDomainID = domainIDTextField.getText();

        OPSIDLProject.defaultProperties.setProperty(new Property("vsExampleTopicName", vsExampleTopicTextField.getText()));
        OPSIDLProject.defaultProperties.setProperty(new Property("vsExampleDataType", vsExampleDataTypeTextField.getText()));
        OPSIDLProject.defaultProperties.setProperty(new Property("vsExampleEnabled", vsExampleEnableCheckBox.isSelected() + ""));
        OPSIDLProject.defaultProperties.setProperty(new Property("vsExampleDomainID", vsExampleDomainTextField.getText()));

        OPSIDLProject.saveDefault();
    }

    boolean valid()
    {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDllDepButton;
    private javax.swing.JButton addJarDepButton;
    private javax.swing.JCheckBox buildCsCheckBox;
    private javax.swing.JCheckBox buildDebugProjectCheckBox;
    private javax.swing.JCheckBox buildJavaCheckBox;
    private javax.swing.JButton changeDefaultConfigFileButton;
    private javax.swing.JLabel defaultConfigFileLabel;
    private javax.swing.JTextField defaultConfigFileTextField;
    private javax.swing.JList dllDepList;
    private javax.swing.JTextField domainIDTextField;
    private javax.swing.JCheckBox genConfigFromSourceCommentsCheckBox;
    private javax.swing.JCheckBox genCppCheckBox;
    private javax.swing.JCheckBox genCsCheckBox;
    private javax.swing.JCheckBox genJavaCheckBox;
    private javax.swing.JTabbedPane godeGeneratorsTabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jarDepList;
    private javax.swing.JButton removeDllDepButton;
    private javax.swing.JButton removeJarDepButton;
    private javax.swing.JTextField vsExampleDataTypeTextField;
    private javax.swing.JTextField vsExampleDomainTextField;
    private javax.swing.JCheckBox vsExampleEnableCheckBox;
    private javax.swing.JTextField vsExampleTopicTextField;
    // End of variables declaration//GEN-END:variables
}
