package pizza.special;

/*This is a really nice Pizza!*/
class ExtraAllt extends LHCData
{
    /*Does the order include extra cheese???*/
    //The above comment is not up to dte and should be removed...
    boolean extraCheese;

    /*@limits(0,INFINITY)*/
    byte nrOfMushRooms;
    int meetQuality;
    long timestamp;
    float timeBakedHours;
    double timeBakedSeconds;
    string description;

    abstract pizza.special.Cheese cheese;

    boolean[] bools;
    byte[] bytes;
    int[] ints;
    long[] longs;
    float[] floats;
    double[] doubles;
    string[] strings;

    pizza.special.Cheese[] cheeses;




}