/*
 * TreeView.java
 *
 * Created on den 25 april 2008, 22:44
 */
package opsdebugger2.topicbrowser;

import java.util.ArrayList;
import opsdebugger2.*;
import java.util.Vector;
import opsdebugger2.proxy.TopicSubscriberProxy;

/**
 *
 * @author  angr
 */
public class TreeView extends javax.swing.JPanel
{

    /** Creates new form TreeView */
    public TreeView()
    {
        initComponents();

        tree.setDragEnabled(true);
        //updateTopics();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        topicsComboBox = new javax.swing.JComboBox();
        manageJarsButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(opsdebugger2.OPSDebugger2App.class).getContext().getResourceMap(TreeView.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tree.setModel(null);
        tree.setName("tree"); // NOI18N
        jScrollPane1.setViewportView(tree);

        topicsComboBox.setName("topicsComboBox"); // NOI18N
        topicsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                topicsComboBoxItemStateChanged(evt);
            }
        });

        manageJarsButton.setText(resourceMap.getString("manageJarsButton.text")); // NOI18N
        manageJarsButton.setName("manageJarsButton"); // NOI18N
        manageJarsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageJarsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topicsComboBox, 0, 208, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageJarsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageJarsButton)
                    .addComponent(topicsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void topicsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_topicsComboBoxItemStateChanged
// TODO add your handling code here:
    TopicSubscriberProxy prx = new TopicSubscriberProxy((String) topicsComboBox.getSelectedItem());

    OPSDebugger2App.setActiveSubscriberProxy(prx);


    tree.setModel(prx);
    tree.updateUI();
}//GEN-LAST:event_topicsComboBoxItemStateChanged

private void manageJarsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageJarsButtonActionPerformed

    updateTopics();

}//GEN-LAST:event_manageJarsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageJarsButton;
    private javax.swing.JComboBox topicsComboBox;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

    private void updateTopics() 
    {

        ArrayList<String> topics = OPSDebugger2App.getActiveProject().getOPSFactory().listTopicNames();
        topicsComboBox.removeAllItems();

        for (String string : topics)
        {
            topicsComboBox.addItem(string);
        }
        topicsComboBox.updateUI();
    }
}
